### ISSUE TITLE
Пути до картинок images/maps

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#1]
В app.min.css есть кривые пути до статики:

background-image:url(images/layers.png)
background-image:url(images/layers-2x.png)
background-image:url(images/marker-icon.png)

возможно, что–то пропустил.

**Comment by allkrain** [comment]
Эти пути тянет из модуля карт. В нашем сss они потом переопределяются. Пусть я даже в этом случае вытащу и поправлю руками этот стиль. А если потом подобная проблема возникнет с другим плагином?

**Comment by vgaicuks** [comment]
Ок, оставим, как есть.
