### ISSUE TITLE
состояние выбора у списков + js

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#10]
в файле ```form-element.js``` на 292 и 303 сточках есть такой код:
```javascript
if (value !== 'placeholder' && container.length > 0)
```
по правилам если список не выбран, то значение value должно быть пустым: ```value=""```, а не **placeholder** иначе при субмите поле равно **placeholder**.

Правильно будет заменить на ```value !== ''```.

**Comment by allkrain** [comment]
Сделано
