### ISSUE TITLE
Неверные индексы в input тегах на 4 шаге

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#11]
На форме загрузке файлов https://verstaburo.github.io/Space-pool/new-space-step41.html при drag&drop сразу нескольких файлов индексы в атрибуте name стоят не верные – все одинаковые. 

Например, при дропе 3 файлов, названия должны быть name="photo[0]", name="photo[1]", name="photo[2]", а сейчас у всех name="photo[2]"

**Comment by allkrain** [comment]
Исправлено

**Comment by vgaicuks** [comment]
Спасибо, работает :)
