### ISSUE TITLE
Popup: Add rental offer

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#12]
На subj. попапе в каждом табе одинаковые формы, это не совсем правильно.

Мы уже это фиксили [тут](https://github.com/verstaburo/Space-pool/issues/3#issuecomment-464142548_)

Правильно будет 1 форма, а вместо табов radio buttons.

**Comment by allkrain** [comment]
Готово

**Comment by vgaicuks** [comment]
Спасибо
