### ISSUE TITLE
Загрузка фоток и алгоритм взаимодействия

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#13]
У нас есть проблема с загрузкой фоток на сервер во время добавлении фоток при создании/редактировании спейса. 
Суть проблемы в том, что мы не знаем точно **когда** и **какой** ```input``` будет заполнен.

Не уверен, что это лучшее решение, но, возможно, в функции ```processingImages```  можно тригерить ивент для ```input``` только–что загруженного файла. Мы будет его ловить и грузить на сервер? 

В момент загрузки на сервер было бы клево отобразить лоадер юзеру.

Какие ваши мысли на этот счет?

**Comment by allkrain** [comment]
Вообще по факту инпуты я выбрала для реализации, чтобы они отправлялись на сервер при отправке формы. Если все упирается именно в перехват файлов, то ловить их надо в момент загрузки, т.е. по событию drop на '.js-upload-file' или change на '.js-upload-file input'

**Comment by vgaicuks** [comment]
Мне кажется, вы не совсем поняли в чем у нас проблема.

При дропе 100 файлов в ".js-upload-file" мы поймаем change ивент, но мы **не знаем** когда именно контент этих файлов будет доступен в создаваемых processingImages инпутах.

**Comment by allkrain** [comment]
На input будет срабатывать событие IMG_READY_FOR_LOAD после добавления всей карточки в DOM. 
Лоадер можно отобразить добавив родительской карточке .photo-preview класс is-load

**Comment by vgaicuks** [comment]
Спасибо, с лоадером все ок – работает.

А вот с ивентом – нет :( он срабатывает до того, как .val() заканчивает свою работу. Поэтому .val() надо обернуть в промис и после выполнения сделать триггер ивенту. Т.к. используется jQuery, то можно использовать его промисы и код может выглядить так:
```javascript
var input = $(preview).find('input[type="hidden"]');
$.when(input).val(e.target.result)).then(function() {
    input.trigger('IMG_READY_FOR_LOAD');
} );
```

**Comment by allkrain** [comment]
Изменила на ваш вариант

**Comment by vgaicuks** [comment]
Спасибо – новый ивент приходит и работает.

Не могли бы убрать Ваш старый триггер ивента?

**Comment by allkrain** [comment]
Извените. Случайно вместо старого триггера удалила соседнюю строчку. Исправлено

**Comment by vgaicuks** [comment]
Спасибо, работает.
