### ISSUE TITLE
Удаление спейсов

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#14]
Еще одна проблема это физическое удаление спейса на бекенде.

На данный момент при удалении спейса, он сразу удаляется из DOM, но что–то может пойти не так на бекенде и удаление не произойдет :( 

Какие будут идеи на механизм взаимодействия? Возможно через ```data-callback```  аттрибут указать Promise функцию по результату которой удалять или не удалять спейс из DOM? Мы заменим на свою функцию, что позволит Вам показывать дизайнерам сайт, а нам контролировать удаление?

**Comment by allkrain** [comment]
Я плаваю в теме промизов. Я могу поместить в data-callback функцию из window и вызвать ее при удалении, но как поместить туда промиз я понятия не имею.

**Comment by vgaicuks** [comment]
Видимо Вы удалили сообщение, но судя по всему есть проблема с написанием js. Код может выглядить как–то так:
```html
<a data-callback="deleteOnBackend" ...></a>
```
При клике делаете что необходимо, но .remove() из DOM вызываем
```javascript
var fn = a.data("callback");
windows[fn]().then(function(){
  space.remove()
})
```
Ваша версия "deleteOnBackend" может быть пустышкой, чтоб демонстрировать клиенту
```javascript
function deleteOnBackend(){
  return new Promise(function(resolve){
    resolve();
  })
}
```

**Comment by allkrain** [comment]
Спасибо. Добавлено

**Comment by vgaicuks** [comment]
Мы не все до конца продумали и пропустили вариант, когда не надо удалять :)) Поэтому надо возвращать true/false

```javascript
var fn = a.data("callback");
windows[fn]().then(function(delete){
  if (delete){
    space.remove();
  }
})
```
Ваша версия "deleteOnBackend" может быть пустышкой, но возвращать true
```javascript
function deleteOnBackend(){
  return new Promise(function(resolve){
    resolve(true);
  })
}
```

**Comment by vgaicuks** [comment]
И еще Вы этот функционал добавили на удаление файлов спейсов (что тоже правильно), но мы просили на удаление самого спейса.

**Comment by allkrain** [comment]
Тогда поясните на какой странице или о каком объекте идет речь.

**Comment by vgaicuks** [comment]
[На этой стрнице](https://verstaburo.github.io/Space-pool/host-spaces.html) списка спейсов у хоста, есть линк с классом "js-delete-object"

**Comment by allkrain** [comment]
Сделано

**Comment by vgaicuks** [comment]
Спасибо. Мы опять были не на высоте и забыли указать, что необходимо передавать удаляемый объект, как параметр.

Добавьте self в deleteObjects.js:17 и $(el) в uploader.js:183 

```javascript
window[fn](self).then((redyDelete) => {
```
ну и соответственно принимать его в функции заглушки

```javascript
function deleteOnBackend(obj) ..
```

**Comment by allkrain** [comment]
Сделано

**Comment by vgaicuks** [comment]
Спасибо.
