### ISSUE TITLE
Класс is-readonly для выпадающих списков

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#15]
Если выпадающий список с классом is-readonly выводится с лейблом, 
```html
<label class="form-box">
  <div class="is-readonly choices">
      ....
  </div>
</label>
```
то js, который поднимает их вверх ломает функциональность readonly и список доступен для выбора значений.

**Comment by allkrain** [comment]
Реально на вашей стороне сделать так чтобы form-box для таких селектов был тэг div. а не label?

**Comment by vgaicuks** [comment]
Спасибо.
