### ISSUE TITLE
Нарезка контента в "Popup legal formalities"

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#18]
Содержания попапа "Popup legal formalities" нам необходимо перенести в pdf формат. 
Мы используем wkhtmltopdf для этих целей, но проблема в том, что этот инструмент не отображает коррекнтно свойство "display: flex" ![Screen_Shot_2019-06-27_at_13_15_35](https://user-images.githubusercontent.com/442747/60258456-d62d5400-98dd-11e9-92f8-f0b0289f591b.png)

Есть ли возможность переделать на table или на float? Это должно решить проблему.

[Пример исходника](https://spacepool.dev.trialine.lv/contracts/1/legal-formalities/) для генерации pdf:

**Comment by allkrain** [comment]
С тем же успехом я могу спросить почему бы не использовать альтернативу wkhtmltopdf типа puppeteer?

**Comment by vgaicuks** [comment]
Отвечаю - технологии и инфраструктура необходимая для решения на wkhtmltopdf отработана.

Мы обязательно протестируем нарезку на puppeteer.

**Comment by allkrain** [comment]
Пока из более менее быстрой альтернативы могу лишь попробовать настроить автопрефиксер для древних версий сhrome >=13, как указано у них в isuues для flex

**Comment by vgaicuks** [comment]
Нее, не стоит. На puppeteer выглядит, в целом ОК, по крайней мере то, что не работает в wkhtmltopdf.

**Comment by vgaicuks** [comment]
Алла, может есть идеи в чем может быть проблема отсутствия "точек" в списках в pdf через puppeteer?

![Screen_Shot_2019-06-27_at_14_23_24](https://user-images.githubusercontent.com/442747/60262653-56a48280-98e7-11e9-9d84-3caeb41ef615.png)

**Comment by allkrain** [comment]
Возможно это из-за того, что они сделаны через ::before
