### ISSUE TITLE
Popup в системных сообщениях

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#19]
В Passport deal есть сообщения, которые работают по технологии websocket - пушатся в интерфейс юзера без перезагрузки страницы и когда прилетает такое сообщение с кнопкой отркывающий попап, то код:
```javascript
$('.js-popup').fancybox(optionsStPopup);
$('.js-popup-mobile').fancybox(optionsMobPopup);
```
не отрабатывает.

Надо переделать что–то в стиле
```javascript
$(document).on('click', '.js-popup', (evt) => {
```

**Comment by allkrain** [comment]
Сделано

**Comment by vgaicuks** [comment]
спасибо.
