### ISSUE TITLE
Скрытие/появление полей в попапе Add rental offer

### ISSUE THREAD

**Issue by alexxxxey** [verstaburo/Space-pool#20]
Нам необходима возможность показывать поле в двух табах, а в двух остальных скрыть:

`<div class="grid__col grid__col_xl_12" data-form-element="meeting-room,hot-desk">`

проблема, что data-form-element принимает только одно значение. Можно ли расширить, что бы можно было через запятую указать для каких показывать поле.

**Comment by allkrain** [comment]
Для этого у <input class="tab-radio__input" data-show-elements="hotDesk" data-hide-elements="dedicatedDesk,meetingRoom,officeSpace" data-toggle-form="data-toggle-form"> есть поля data-show-elements и data-hide-elements - в них как раз через запятую можно перечислить наименование элементов data-form-element, которые будут соответственно показаны и скрыты при выборе этого значения.
