### ISSUE TITLE
disabled dates для Air datepicker

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#21]
Необходима возможность задавать даты, которые только readonly

**Comment by allkrain** [comment]
Можно подробнее, что именно надо. У input c readonly перестал работать value?

**Comment by vgaicuks** [comment]
Неа, суть проблемы в другом. По бизнесу в календаре могут быть даты, которые пользователь не может выбрать, вот эти даты я назвал "disabled dates".

**Comment by allkrain** [comment]
Обновлены скрипты для календарей. У элемента, к которому привязан datepicker прописать атрибут data-disabled-dates="2019-8-2,2019-8-5,2019-8-20,2019-8-14"

**Comment by vgaicuks** [comment]
Спасибо.
