### ISSUE TITLE
Ивенты на любой клик 

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#22]
[На странице ](https://verstaburo.github.io/Space-pool/space.html#popup-arrange-viewing) где акардион (Offers) в диве класса "offer-short__buttons" весит ивент, который ловит все клики и у нас нету возможноти прописать рабочий href атрибут для ```<а href=""``` тэга.

**Comment by allkrain** [comment]
Исправлено

**Comment by vgaicuks** [comment]
Сорян, за долгий респонс, но ивент все еще висит :(

**Comment by allkrain** [comment]
Сделано
