### ISSUE TITLE
Есть ли возможность заблокировать все даты до сегодня в виджете?

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#24]
subj.

**Comment by allkrain** [comment]
Обновила код сейчас по умолчанию для всех элементов с datapicker начальная  дата будет установлена в текущую. Но сделала возможность изменить ее для этого ввела параметры data-mindate и data-maxdate - устанавливают минимально и максимально допустимую дату соответственно. Чтобы не устанавливать минимальную дату в текущую задайте параметр data-mindate таким образом data-mindate=''
