### ISSUE TITLE
Margin в "Popup Add rental offer" попапе

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#27]
При открытии попапа "Popup Add rental offer", есть дергание и ненужный отступ.

**Comment by allkrain** [comment]
Этот отступ был добавлен для всех попапов с непостоянной высотой, чтобы когда размер формы меняется верхняя граница не уезжала ниже или выше если размер сильно уменьшился или сильно увеличился (так захотели дизайнеры)

**Comment by allkrain** [comment]
Больше не скачет
