### ISSUE TITLE
Event на crop фотки

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#28]
Будьте добры добавить ивент (или какой–нибудь флаг) на действие, когда юзер делает crop фотки [тут](https://verstaburo.github.io/Space-pool/new-space-step41.html).

До этого, после crop добавлялся тэг ```<input name="photoCrop">``` с value="фотка" , мы к этому подвязались, но сейчас это уже не работает :(

**Comment by allkrain** [comment]
Ивент сrop добавляет плагин на изображение исходник [data-crop-image]. Ну либо отслеживайте ивент change на добавляемом после обрезки инпуте с атрибутом data-file-crop. Описание методов плагина можно найти здесь: https://github.com/fengyuanchen/cropperjs/blob/master/README.md. Должны быть доступны в свойстве $('[data-crop-image]')[0].cropper

**Comment by vgaicuks** [comment]
Спасибо за помощь.
