### ISSUE TITLE
Сломался виджет даты

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#29]
При нажатии на иконку календаря не открывается виджет. Поле Date of birth [тут](https://verstaburo.github.io/Space-pool/signup-host-info.html). 
P.S. это что–то глобально, в других местах такой же эффект.

**Comment by allkrain** [comment]
Исправлено. 
P.S. Теперь чтобы в календаре были все даты нужно использовать конструкцию data-mindate="all"

**Comment by vgaicuks** [comment]
Спасибо!
