### ISSUE TITLE
Signup.html

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#3]
Ребята, можно узнать причину создания 2 одинаковых форм в signup.html файле?
На первый взгляд, правильнее (DRY) было бы обойтись 1 формой.
Из–за этого parsley при активном табе "Sign Up as host" ошибочно считает, что пароли не совпадают.

Есть ли возможность перейти на 1 форму?

**Comment by allkrain** [comment]
Проблема не в двух формах, а в одинаковых идентификаторах в атрибуте data-parsley-equalto у паролей (я поменяла сейчас - проблемы быть не должно). А на счет двух одинаковых форм, если бы переключатели были задуманы как радиокнопки, а не табы я бы сделала одну форму, но это не так, поэтому форм две.

**Comment by vgaicuks** [comment]
По дизайну бекенда да и по своей сути это одна форма. Radio buttons надо стилизовать под табы.

**Comment by allkrain** [comment]
Я спрашивала радиокнопки это или табы - мне сказали табы

**Comment by vgaicuks** [comment]
У кого Вы спрашивали? У дизайнеров?

**Comment by allkrain** [comment]
Да

**Comment by vgaicuks** [comment]
Визуально они выглядят, как табы, а не radio buttons – дизайнеры не могли дать иного ответа. Или же Вы объяснили, что значение выбранной кнопки будет сохраняться в базу, а дизайнеры ответили – не, сохранять не надо?
Мне придется Вас огорчить, но придется переделать.

**Comment by allkrain** [comment]
Сделано

**Comment by vgaicuks** [comment]
Спасибо.
