### ISSUE TITLE
Разметка на виджете даты

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#31]
При выборе не короткого "May" месяца на попапе "Popup order summary GUEST" дата прыгает на следующую строчку
![image](https://user-images.githubusercontent.com/442747/67276660-d4f7e680-f4cd-11e9-8e35-d4b71e5a0629.png)

**Comment by allkrain** [comment]
Оно не прыгает оно переносится, так как с дизайнерскими отступами не вмещается в этот размер экрана. И какие предложения?

**Comment by allkrain** [comment]
Готово
