### ISSUE TITLE
символы с права на лево в info-editable

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#32]
Добрый день.

Алла, не подскажете, когда поправился баг в data-field-edit полях следующего хараактера: при нажатии на "Edit" и ввода 123 печаталось 321 ?

спасибо.

**Comment by allkrain** [comment]
Мне трудно, что либо здесь подсказать. Так как этой проблемы просто не было. Обычно чтобы текст печатался в обратном направлении в браузере это надо делать специально (так как он по дефолту печатается в left to right).

**Comment by vgaicuks** [comment]
Спасибо за комментарий.
