### ISSUE TITLE
slider в спейсе. Первый слайд.

### ISSUE THREAD

**Issue by alexxxxey** [verstaburo/Space-pool#33]
Привет!
Сломали всю голову. Не можем исправить. Глюк такой, когда дофига фоток и слабенький комп или медленный интернет (в общем все, что вызывает задержку отрисовки), то слайд, который должен быть первым не всегда первый. Вот пример (House of Creative - 225 Shoreditch High Street):
https://photos.app.goo.gl/CkjiAHHjvgTCFuH58

**Comment by allkrain** [comment]
Здравсвуйте!
Я обновила плагин слайдера до последней версии и внесла несколько корректировок в настройки. Если не поможет, то можно попробовать включить lazy-load, но придется переписывать атрибуты у изображений

**Comment by alexxxxey** [comment]
Спасибо, будем смотреть
