### ISSUE TITLE
Message list в хедере

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#35]
Как можно вывести текст по центру, как в скриншоте, когда у пользователя чат пуст?
Не очень получается это сделать.
Спасибо.

![message-list](https://user-images.githubusercontent.com/442747/72149044-e2c15780-33aa-11ea-98ce-dfb4dabf840e.png)

**Comment by allkrain** [comment]
Поскольку дизайнеры такого состояния не предусмотрели, то прямо сейчас никак. Нужно писать отдельный стиль. Например задать info-notice__wrapper класс при добавлении которого ему пропишутся стили justify-content: center; align-items: center; padding-left: 6px; padding-right: 6px;

**Comment by vgaicuks** [comment]
Спасибо!
