### ISSUE TITLE
Есть ли возможность отключить сортировку?

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#36]
Если возможность отключить сортировку ?

![screen-1](https://user-images.githubusercontent.com/442747/72428682-e122d580-3796-11ea-934a-f568a9090379.png)

Мы уже выводим в нужном порядке options, которые клиент регулирует в админке:

![screen-2](https://user-images.githubusercontent.com/442747/72428777-0ca5c000-3797-11ea-84dd-d1b247f27697.png)

**Comment by allkrain** [comment]
Я добавила в js изменения - добавьте селекту атрибут data-no-sort="data-no-sort" должно отключить сортировку

**Comment by vgaicuks** [comment]
Спасибо!
