### ISSUE TITLE
Добавить возможность вызывать функцию textareaAutosize

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#37]
Можете добавить функцию textareaAutosize в окружение window? У нас через ajax подгружаются textarea элементы и у них не работает autosize.

**Comment by allkrain** [comment]
window.autosizeTextarea - без аргументов отработает на всех элементах. Но можно передать отдельные элементы в качестве аргумента

**Comment by vgaicuks** [comment]
Большое спасибо за оперативность. Все работает замечательно.
