### ISSUE TITLE
Нужна возможность установить дату

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#38]
Нужна возможность поменять дату которая показывается при открытии календаря (js-datepicker).

Спасибо.

**Comment by allkrain** [comment]
По сути данная возможность должна быть доступна для этого плагина из коробки $('.js-datepicker').datepicker().data('datepicker').date = new Date();

**Comment by vgaicuks** [comment]
Мы попробовали установить, но в таком случае value пропадает.

![image__2_](https://user-images.githubusercontent.com/442747/73662779-11c6a280-46a5-11ea-9012-acfb7be00702.png)

**Comment by allkrain** [comment]
Тогда через $('.js-datepicker').datepicker().data('datepicker').selectDate(new Date());

**Comment by vgaicuks** [comment]
Я перечитал вопрос и осознал, что выразил мысль очень коряво, приношу свои извинения и пишу заново: 

Нужна возможность установить **init** значение для виджета. Если значение поля, например: 27.06.2000, то при открытии календаря виджет показывает 2002 год :(

P.S. При вызове $('.js-datepicker').datepicker().data('datepicker').selectDate(new Date()); появляется кнопка "Save change", хотя юзер лично не делал изменений на форме.

**Comment by allkrain** [comment]
Тогда $('.js-datepicker').datepicker().data('datepicker').update('startDate', new Date()); Или важно, чтобы это было можно сделать через дата параметр например?

**Comment by vgaicuks** [comment]
.update дает такой результат:

![image (3)](https://user-images.githubusercontent.com/442747/73748277-bb6b6980-4761-11ea-8f57-9c087bd85591.png)

Решение через data атрибут нам самое удобное, конечно

**Comment by allkrain** [comment]
Добавила возможность установить data-startdate="1990-7-22"

**Comment by vgaicuks** [comment]
Спасибо большое! Работает.
