### ISSUE TITLE
Нет возможности добавить повторно одну фотку дважды после удаления

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#39]
Как повторить: 

0. [На этой странице](https://verstaburo.github.io/Space-pool/edit-space-images.html)
1. Добавляем фото
2. Удаляем это фото
3. Добавляем ту же фотку, что в пункте 1.
4. Она не добавляется :(

**Comment by allkrain** [comment]
Внесла корректировку

**Comment by vgaicuks** [comment]
Спасибо, работает.
