### ISSUE TITLE
Блок для ошибок в форме, которые возвращает бекенд

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#4]
После submit формы могут появится ошибки, которые можно валидировать только на бекенде, например, уникальности email.
На данный момент блок `<div class="error-message"></div>` используется для вывода parsley ошибок и бекенд ошибок. Это приводит к ситуации, где нельзя контролировать бекенд ошибки после ввода юзером информации еще раз. 

Сценарий: Юзер ввел имейл -> нажал субмит -> ошибка в поле имейл "Такой имейл уже зарегестрирован" -> юзер вводит другой мейл, допуская опечатку -> показываются 2 ошибки "Неверный формат имейла" и "Такой имейл уже зарегестрирован"

Как вариант, можно сделать еще один `<div class="error-message__server"></div>`
Что думаете?

**Comment by allkrain** [comment]
Добавить-то можно. Вы будете его чистить когда пользователь будет менять input? Иначе это все бессмысленно.

**Comment by allkrain** [comment]
Кроме того Вы просто можете генерировать ошибку обернутую в подобную конструкцию и добавлять ее в тот же error-message. Только сам error-message показывается пользователю, когда у поля с ошибкой у родительского элемента form__wrapper стоит класс is-error.

**Comment by vgaicuks** [comment]
Спасибо. Пока остановимся на этом решении.
