### ISSUE TITLE
Сделать динамическим activeStep в cancelationPopupSteps.js

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#40]
На сайте, cancelationPopupSteps динамичны, но решение `activeStep === 'step4'` в cancelationPopupSteps.js:93 нас ограничивает.

`if (readySaved && activeStep === 'step4') {`

Можете получать  'step4' через data атрибут, который будет у "self"?

например:

 `if (readySaved && activeStep === $(self).attr('data-call-additional-form-from-step')) {`

**Comment by allkrain** [comment]
Сделано

**Comment by vgaicuks** [comment]
Спасибо! Правда мы еще не встроили это изменение, пусть еще тут полежит.

**Comment by vgaicuks** [comment]
Спасибо.
