### ISSUE TITLE
Choices вырезает все кастомные атрибуты

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#42]
Плагин Choices вырезает все кастомные (data-*) атрибуты ```<option>```  тэга, одним словом ведет себя очень дерзко :))

Можно ли договориться о именах атрибутах, которые не надо вырезать?
Например, data-custom-1, data-custom-2, data-custom3 – думаю нам должно этого хватить.
Или, например, data-custom-* не вырезать вообще?

P.S. можно и другое решение.

**Comment by allkrain** [comment]
Единственный data- атрибут, который он переносит на селект после инициализации насколько знаю это data-custom-properties - Вот в него можно засунуть при желании строку с json

**Comment by vgaicuks** [comment]
Спасибо, работает.
