### ISSUE TITLE
Мобильная версия меню

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#45]
Для реализации  сообщений и нотификаций в хедере мы используем реактивные компоненты Vue.js + вебсокеты, но мобильная версия этих же элементов вынесена в другое место. После попытки поставить нарезку в компоненту, меню не прижато в bottom и перекрывается шторкой слева.

Есть идеи, как это можно поправить?

Тестовый пример тут: https://spacepool.dev.trialine.lv/ 
Basic auth: t/trialine
SignIn в спейспул: vital+1@trialine.lv/Password1#

**Comment by allkrain** [comment]
А можно как-нибудь на скрине обозначить проблему, по описанию не совсем понятно. А тут https://spacepool.dev.trialine.lv/ основную проблему вижу в том, что из-за внешних оберток у блока панельки с элементами интерфейса с низу например z-index работает не корректно из-за чего она проваливается под картинки, карты и объекты.

**Comment by vgaicuks** [comment]
Есть 2 проблемы:
1) Концептуальная, что мобильная версия это совершенно другая нарезка. Получается, компонента нотификаций дублируется по контенту один в один. Тут мы делаем костыль по брейкпоинту меняем нарезку в компоненте, но т.к. меню мобильный версии сделано где–то даааааалеко от хедера десктопа, а мы его пихаем в `<nav>`, то появляется вторая визуальная проблема

2) Надо скролить в самый низ, чтоб увидеть меню
![header-bottom](https://user-images.githubusercontent.com/442747/77917017-9fd49900-72a2-11ea-82b2-7a4e1e833047.png)

панель сообщений и уведомлений перекрывает меню
![overflow](https://user-images.githubusercontent.com/442747/77917149-d6aaaf00-72a2-11ea-839e-45a40732b7cb.png)

**Comment by allkrain** [comment]
Все эти проблемы именно от внешнего div у панельки - дайте ему настройки панельки хотябы в части z-index и position

**Comment by vgaicuks** [comment]
Да понятно, что проблема в том, что user-menu-panel поместили в хедер. Mы поэтому и создали тут issue. Похоже вы не понимаете в чем наша боль. А она в том, что мобильная версия это не адаптивная версия, а вообще другая верстка. И сообщения, которые прилетают надо вставлять и в header-user__user блок, и в user-menu-panel, получается мясо.

Возможно, с такими запросами дизайнеров сделать иначе это на гране фантастики.

**Comment by allkrain** [comment]
Как раз сообщения нужно вставлять просто так же как панель под хэдер, а не в него. Возможно с этим у вас и связаны проблемы с ними в сафари.

**Comment by vgaicuks** [comment]
Спасибо, звучит обнадеживающе. Сейчас попробуем.

**Comment by vgaicuks** [comment]
Спасибо большое. Это реально помогло. Сорян, был не прав на счет message-list и event-list - он действительно не дублируется.

Все получилось хорошо, спасибо еще раз.
