### ISSUE TITLE
Интеграция нового дизайна

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#47]
Дизайнеры готовят редизайн spacepool.com, после интеграция первой версии у нас были трудности, которые хотелось бы избежать для уменьшения расходов.

Самая большая боль это формы, которые для десктопа и мобильных версий были разной нарезки. 
В проекте мы используем Django фреймворк, который поля формы выводит в виде {% form.field_name %}. Это приводило к костылям, для избежания дубликатов id атрибутов, вывода ошибок (т.к тут тоже нарезка отличалась).

Есть ли какая–то возможность этот процесс усовершенствовать, сделав формы более адаптивными?

P.S. Это не наезд, это попытка сделать процесс интеграции более продуктивным.

**Comment by allkrain** [comment]
Что понимается под адаптивностью в данном случае? Я не против усовершенствования процесса, но давайте больше конкретики. Но многое так же будет зависеть от того насколько будет отличатся дизайн одной и той же формы в мобильном представлении и в десктопном. На сколько могу предположить по дублированию форм основные претензии должны быть к попапам или нет?

**Comment by vgaicuks** [comment]
Под адаптивностью я имел ввиду такую нарезку, которая не требует другой версии, а динамически меняется в зависимости от ширины экрана за счет css классов.

Да, Вы правы, основные претензии к формам в попах. 

Например, "Popup cancel request" это хороший вариант, а вот "Popup order summary HOST" это "проблемный" пример.
