### ISSUE TITLE
Choices вырезает option с value=""

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#53]
На странице https://verstaburo.github.io/Space-pool/host-reservations.html есть косячок описанный в subj.

Есть возможность это поправить? Изменения комитить в мастер бранч.

**Comment by allkrain** [comment]
По сути он их не выпиливает, а просто вешает класс плейсходера (такая у него фича), а у элементов плейсхолдера стоит display: none - в выпадающем списке. Конечно можно убрать display: none и поправить стили в выпадашке у плейсхолдеров. Но это будет глобально везде - а не только на указанной странице (Т.е. если где-то реально указана опция с плейсхолдером - она выплывет в выпадающем списке). Учитывая все выше - корректировать стили?

**Comment by vgaicuks** [comment]
Да, корректировать.

Спасибо.

**Comment by allkrain** [comment]
Готово

**Comment by vgaicuks** [comment]
Спасибо.
