### ISSUE TITLE
Нужна возможность вызвать SearchFilter.init() из вне

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#55]
Форма поиска в нашем решении подгружается динамически из–за этого js ивенты повешенные на нее не срабатывает. 

Можно ли сделать доступным вызов SearchFilter.init из наших скриптов?

**Comment by allkrain** [comment]
Если нужна функция которая бы делала вот это вместе `const filter = new SearchFilter(el);
      filter.init();` то я добавила функцию window.globalFunctions.searchFilterInit(<элемент фильтра .filter-menu>). Если нужен именно только доступ к методу init, то у элемента при инициации теперь образуется свойство searchFilter, через него должно быть возможно получить доступ к этому методу.

**Comment by vgaicuks** [comment]
window.globalFunctions.searchFilterInit(<элемент фильтра .filter-menu>) - это именно то, что нужно

**Comment by vgaicuks** [comment]
спасибо.

**Comment by vgaicuks** [comment]
@allkrain есть проблемка, при вывозе globalFunctions.searchFilterInit валится с ошибкой:

Cannot set property 'searchFilter' of undefined

```javascript
    window.addEventListener('load', function() {
      // console.log('DOM ready')
      window.globalFunctions.searchFilterInit(form)
    })
```
по каким–то причинам globalFunctions еще не доступен, можете что–то посоветовать, кроме как setTimeout ?

**Comment by allkrain** [comment]
Ну как вариант можно попробовать привязать вызов этой функции напрямую атрибут  к onload у нашего скрипта. `<script src="app.js" onload=""></script>`. Ну или могу добавить вызов какого-нибудь триггера после инициализации window.globalFunctions.searchFilterInit и сможете ориентироваться на него. Ну и глупый вопрос вызов ведь расположен  после нашего скрипта?

**Comment by vgaicuks** [comment]
Мы пересобираем весь js и Ваш и наш используя webpack, другими словами у нас одий файл js, но ваши предложения навели на мысль и мы нашли решение. 

Спасибо большое.
