### ISSUE TITLE
Нет возможности добавить ивент на кнопку 

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#58]
[На странице](https://verstaburo.github.io/Space-pool/space-v3.html) на кнопку "Request reservation" нам надо повесить логику, но ивент не отрабатывает, видимо акардион его перехватывает
<img width="1245" alt="Screen Shot 2020-09-10 at 17 51 32" src="https://user-images.githubusercontent.com/442747/92748904-46fb4780-f38e-11ea-9c05-797fd7fba12d.png">

**Comment by allkrain** [comment]
Я как бы пыталась избежать этой проблемы и повесила перехват на родительский блок с атрибутом data-blind-zone. Можете убрать атрибут data-blind-zone у offer-card__buttons и перехватчик больше не будет работать.

**Comment by vgaicuks** [comment]
Спасибо, попробуем

**Comment by allkrain** [comment]
Изменила принцип действия blind-zone на аккордеоне - возможно удаление не потребуется

**Comment by vgaicuks** [comment]
спасибо.
