### ISSUE TITLE
Нужна глобальная функция для инита бегунка в виджете price range

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#59]
subj. [для формы поиска](https://verstaburo.github.io/Space-pool/search-types.htm)

**Comment by allkrain** [comment]
Добавила window.globalFunctions.rangeInit

**Comment by vgaicuks** [comment]
Спасибо, бегунок появился, а вот плейсхолдеры наползли на инпуты, что еще надо вызвать?

<img width="494" alt="Screen Shot 2020-09-10 at 20 03 54" src="https://user-images.githubusercontent.com/442747/92768524-c3972180-f3a0-11ea-941e-b748a7587aeb.png">

**Comment by allkrain** [comment]
Вроде раньше уже было window.setLabelPosition, window.setLabelListeners

**Comment by vgaicuks** [comment]
Спасибо, припамятовал window.setLabelPosition.

Есть еще 2 вопроса по поводу бегунка:
1. Как установить значение в инпуты, чтоб noUiSlider его респектовал
2. Как поймать ивент, когда юзер мышкой устанавливает значения инпутов (change его не ловит)

**Comment by allkrain** [comment]
Просто слушайте событие не на ипутах, а на бегунке события возникают на элементе с атрибутом data-nd-range-container. Прослушку я вешала примерно так `$('[data-nd-range-container]').get(0).noUiSlider.on('change', (values, handle) => {});`. Вот ссылка на события которые можно слушать https://refreshless.com/nouislider/events-callbacks/

**Comment by allkrain** [comment]
Передать значения из инпутов в бегунок можно через метод `sldr.noUiSlider.set([minVal, maxVal]);`, где sldr - это элемент data-nd-range-container. Собственно они сейчас передаются, но только после потери фокуса в инпуте.
