### ISSUE TITLE
app.css

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#6]
Есть ли возможность в dist/assets/styles выкладывать не минимизированный css?
Это может сильно облегчить интеграцию.

**Comment by allkrain** [comment]
Я убрала минификацию сss из процесса сборки, но префикс min у файла остался. Теперь минификация css на вас.

**Comment by vgaicuks** [comment]
Спасибо это реально помогает. Да, мы сами сделаем минификацию.
