### ISSUE TITLE
Виджет календаря не респектует data-mindate

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#60]
![Screen Shot 2020-09-15 at 16 31 13](https://user-images.githubusercontent.com/442747/93228371-10eb0880-f77e-11ea-9e79-d2dcdb1e38c5.png)

**Comment by allkrain** [comment]
У вас судя по картинке отключены даты до 15 числа включительно, а внизу указана дата 10. Вы меняли дату в атрибуте? Проблема в том, что после изменения даты в атрибуте диапазон не меняется так?

**Comment by allkrain** [comment]
Исправлено

**Comment by vgaicuks** [comment]
спасибо
