### ISSUE TITLE
Google info window

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#61]
Можете сделать тайтл спейса и картинку в виде ссылки ибо при клике надо редиректить на объект

![Screen Shot 2020-09-16 at 15 52 35](https://user-images.githubusercontent.com/442747/93340785-fd9b7400-f835-11ea-9d9c-090c6faaaaf5.png)

**Comment by allkrain** [comment]
Ccылка будет общая для всех элементов или индивидуальная для каждого?

**Comment by allkrain** [comment]
Добавлено

**Comment by vgaicuks** [comment]
Ну как, у каждого спейса своя.

**Comment by allkrain** [comment]
То, что у каждого своя понятно. Имелось ввиду у тайтла и картинки одна и та же или разные. Сейчас сделана одинаковая в рамках одного спейса.

**Comment by vgaicuks** [comment]
Спасибо.
