### ISSUE TITLE
Поменять формат rent start date  с 2020-09-16 на 16 September 2020

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#62]
subj. на https://verstaburo.github.io/Space-pool/rental-summary.html

![Screen Shot 2020-09-16 at 15 59 11](https://user-images.githubusercontent.com/442747/93340978-39ced480-f836-11ea-8860-e5146dc7388d.png)

**Comment by allkrain** [comment]
Попробуйте у js-nd-datepicker прописать data-dates-result-format="D MMMM YYYY". Поскольку форматирую через momentjs то список обозначений для форматирования https://momentjs.com/docs/#/displaying/format/

**Comment by vgaicuks** [comment]
Спасибо.
