### ISSUE TITLE
Форма поиска по location

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#63]
От чего зависит и как решить следующий кейс на форме [поиска](https://verstaburo.github.io/Space-pool/search.html):

1. Кликаем на All location, выбираем London (почему–то установлены сразу 3 area как это управляется?)
2. После удалем крестиком все выбранные area (см. скриншот)
<img width="905" alt="Screen Shot 2020-09-16 at 16 24 23" src="https://user-images.githubusercontent.com/442747/93343381-18231c80-f839-11ea-9615-f2818b65422e.png">
3. Кликаем на All location -> Bristol -> London опять 3 выбрано в locationAreas.json не нашел каких–то флагов

**Comment by vgaicuks** [comment]
хотя нашел "checked": "checked"

Это что получается, если пользователи заходят на страницу поиска с уже предустановленными значениями, то надо пилить каждому свой json, может можно что–то придумать как установить checked?

**Comment by allkrain** [comment]
Пожалуй, если только проставив соответствующим полям атрибут и свойство checked в true скриптом, и вызвать на них триггер change (чтобы тэги сгенерировать)

**Comment by vgaicuks** [comment]
Разве эти поля (input name="location") не появляются только после получения locationAreas.json? Другими словами нужен ивент, что инпуты появились в DOM или я ошибаюсь?

**Comment by allkrain** [comment]
Не совсем. По locationAreas.json появляются поля (input name="locationPlace"), которые под отчеркиванием. При инициализации фильтра, если у инпута с прописанным json был статус checked - они будут сгенерированы без ивента. В остальных случаях да генерация происходит по ивенту change. Т.е. если мы хотим предустановить статус сhecked на input( name="locationPlace") - на данный момент только ручками или через json. 
Можно конечно написать отдельный метод, который бы вызывался при инициализации фильтров и просто по требованию и брал из какого-то отдельного атрибута предустановленные значения для полей input(name="locationPlace") cкажем по value.
