### ISSUE TITLE
Проблема с календарем при использовании старого и нового дизайна.

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#64]
При использовании нового дизайна с элементами старого. При клике на ссылку открывающую попап(js-popup) 
![Screen Shot 2020-09-18 at 14 31 47](https://user-images.githubusercontent.com/28781981/93592979-e090ad80-f9bb-11ea-8e58-36a9f4662b21.png)

в попапе при клике на дату календарь отображается некорректно.
![Screen Shot 2020-09-18 at 14 28 20](https://user-images.githubusercontent.com/28781981/93593041-fef6a900-f9bb-11ea-868e-4ab4b4115786.png)

Возможно это происходит из-за того, что при открытии попапа, вызывается функция freeze и работает функция закрытия нового меню:
`  $(document).on('click', (evt) => {
    const self = evt.target;
    if ($(self).closest('.nd-main-menu').length === 0 && $(self).closest('.js-open-navigation').length === 0 && $(self).not('.js-open-navigation')) {
      mainNavigation.close();
    }
  });`
которая вызывает функцию unfreeze. 

Ошибку можно посмотреть [тут](https://spacepool.dev.trialine.lv/passport-deal/1575/#popup-order)

[пароли тут](https://onetimesecret.com/secret/oq9nnd647y3ryh7ecye14m7acilj4mv)

**Comment by allkrain** [comment]
Добавила фикс.

**Comment by ASergej** [comment]
Спасибо.
