### ISSUE TITLE
Google info window показывается за границами контейнера карты

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#65]
![image](https://user-images.githubusercontent.com/28781981/93770409-ce657800-fc24-11ea-82ae-a5d52a743ff0.png)
Есть ли возможность в таком случае показывать info window  над маркером?

**Comment by allkrain** [comment]
Добавила функции смещения центра, если элемент скрыт за границей области. Теперь такой проблемы быть не должно.

**Comment by ASergej** [comment]
Спасибо.
