### ISSUE TITLE
Нужна глобальная функция закрытия попапа поиска

### ISSUE THREAD

**Issue by vgaicuks** [verstaburo/Space-pool#66]
subj.

**Comment by allkrain** [comment]
Не совсем поняла о каком попапе идет речь. Пришлите скрин пожалуйста.

**Comment by vgaicuks** [comment]
Вот этот
![image](https://user-images.githubusercontent.com/442747/94229220-a5d0cd00-ff07-11ea-9230-ac84cb248abc.png)

**Comment by allkrain** [comment]
Должно сработать вот это $('[data-nd-filter]').get(0).searchFilter._hideAllFilters();

**Comment by vgaicuks** [comment]
спасибо
