### ISSUE TITLE
Add Space - Photo sorting

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#67]
https://verstaburo.github.io/Space-pool/add-space-photo.html

1. Есть ли возможность проставлять значения, которые проставляет функция updateAllPreviewIndex, в поле с названием spaceimage_set-#fileIndex-sort ?
![Screen Shot 2020-10-01 at 11 53 46](https://user-images.githubusercontent.com/28781981/94788845-d9ff2e80-03dc-11eb-9f13-faabec8ccb31.png)
3. Можно сделать так чтобы updateAllPreviewIndex считала только картинки для которых сработал ивент IMG_READY_FOR_LOAD?

**Comment by allkrain** [comment]
Касательно 1 - если имеется ввиду заполнять им value то думаю это можно реализовать.  Значения, которые на номерке или которые у input?
Касательно 2 - не знаю как бы это можно было реализовать, учитывая что она  просто переименовывает все по порядку следования и на страницах edit у уже существующих карточек этого события не будет. Возможно достаточно, чтобы в переименовании не включались элементы с ошибкой?

**Comment by ASergej** [comment]
1) Заполнить input value значением на номерке
2) Да нам подойдет такой вариант

**Comment by allkrain** [comment]
Пробуйте

**Comment by ASergej** [comment]
Спасибо.
