### ISSUE TITLE
Add Space - Photo

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#68]
https://verstaburo.github.io/Space-pool/add-space-photo.html

1. В прошлой версии этой страницы после срабатывания ивента IMG_READY_FOR_LOAD появлялась анимация загрузки, можно ли в этой версии сделать что-то похожее?
![Screen Shot 2020-10-01 at 12 05 22](https://user-images.githubusercontent.com/28781981/94790144-8ee61b00-03de-11eb-9568-97ee3f6b1b4c.png)
2. После загрузки фото через Upload another этот блок не исчезает, должно ли так быть?
![Screen Shot 2020-10-01 at 11 59 32](https://user-images.githubusercontent.com/28781981/94789604-c7d1c000-03dd-11eb-843d-16e1420af54f.png)

**Comment by allkrain** [comment]
Касательно 1 - я добавлю прелоадер в блок, но вот класс is-load cкорее всего проставлялся на вашей стороне при загрузке на сервер и при удалении с сервера.
Касательно 2 - я как-то об этом не подумала. Внесу корректировку.

**Comment by allkrain** [comment]
Сделано

**Comment by ASergej** [comment]
Спасибо.
