### ISSUE TITLE
Account Settings | Basic info

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#69]
https://verstaburo.github.io/Space-pool/guest-account-basic.html

1. При попытке добавить поля в форму растянулся блок с картинкой пользователя. Может у вас есть идеи как это исправить?
![Screen Shot 2020-10-01 at 12 38 50](https://user-images.githubusercontent.com/28781981/94793484-32392f00-03e3-11eb-8dc8-a02b9cf89375.png)
2. После нажатия Discard changes элемент с кнопками не скрывается.
3. Есть ли возможность покрасить ссылку Delete Current Userpic в серый цвет или скрыть(когда у пользователя не загружено фото)

**Comment by allkrain** [comment]
Касательно 1 - думаю растянулись равномерно оба боковых блока так сработала текущая раскладка блоков. Нужно чтобы растягивался только последний  блок справа или  под ним должно образоваться пустое место?
Касательно 2 - посмотрю. 
Касательно 3 - прямо сейчас чтобы скрыть можно добавить класс nd-hide - элементу.

**Comment by ASergej** [comment]
1) Можете оставлять пустое место?

**Comment by allkrain** [comment]
Поправила

**Comment by ASergej** [comment]
Спасибо

**Comment by ASergej** [comment]
Discard changes не исчезает если добавить select 
![Screen Shot 2020-10-05 at 18 05 07](https://user-images.githubusercontent.com/28781981/95096789-655a2600-0735-11eb-9c14-dec63ee5a5a8.png)

**Comment by allkrain** [comment]
Готово

**Comment by ASergej** [comment]
Спасибо
