### ISSUE TITLE
Index page location search

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#70]
Можно сделать так, чтобы в locations-autocomplete.json мы указывали id скрытого input и автокомплит
 подставлял значение в input с этим id?
![Screen Shot 2020-10-01 at 16 11 20](https://user-images.githubusercontent.com/28781981/94813709-075dd380-0401-11eb-8ec9-7f9246dd01ec.png)
![Screen Shot 2020-10-01 at 16 05 08](https://user-images.githubusercontent.com/28781981/94812933-109a7080-0400-11eb-8cd4-5d87717bec31.png)

**Comment by allkrain** [comment]
Инпут уже будет присутствовать на странице?
PS: Сейчас работает исходя из того, что инпут уже есть. Пробуйте.

**Comment by ASergej** [comment]
Спасибо.

**Comment by ASergej** [comment]
Можно сделать чтобы в locations-autocomplete.json был ключ value и подставлять его содержимое в значение скрытого поля?
![Screen Shot 2020-10-06 at 16 42 31](https://user-images.githubusercontent.com/28781981/95209572-2db1b380-07f3-11eb-8b4a-32c08db34e35.png)

**Comment by allkrain** [comment]
Добавлено

**Comment by ASergej** [comment]
Спасибо
