### ISSUE TITLE
Form errors and vue.js

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#72]
Мы используем vue.js для некоторых частей сайта и всё содержимое body у нас обернуто в элемент к которому присоединяется Vue.
![Screen Shot 2020-10-08 at 14 10 52](https://user-images.githubusercontent.com/28781981/95451229-28c63e80-0970-11eb-9814-ab6438ca1f5c.png)
 И в таком случае ошибки формы вставляются неправильно
![Screen Shot 2020-10-08 at 14 03 34](https://user-images.githubusercontent.com/28781981/95451409-67f48f80-0970-11eb-923c-545f9184e30e.png)
Как только мы выключаем Vue, ошибки подставляются правильно. 
![Screen Shot 2020-10-08 at 14 20 50](https://user-images.githubusercontent.com/28781981/95452191-8e66fa80-0971-11eb-8566-e4de0c90641f.png)

Может у вас есть идеи почему так может происходить?

**Comment by allkrain** [comment]
Вероятно у вас слетают опции parsley к дефолтным. Скорее всего это связано с тем, что опции привязываются к конкретному инстансу. Я попробовала переопределить опции у parsley глобально думаю это должно решить проблему.

**Comment by ASergej** [comment]
Спасибо
