### ISSUE TITLE
Search result item link

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#74]
https://verstaburo.github.io/Space-pool/search-types.html
Нам нужна возможность менять ссылку когда меняется слайд. Может у вас есть идеи как это сделать?
![Screen Shot 2020-10-29 at 16 24 21](https://user-images.githubusercontent.com/28781981/97587085-aaefd300-1a03-11eb-860f-43ffe06cb27c.png)

**Comment by allkrain** [comment]
Думаю варианта может быть 2:
1. убираете тэг 'a' у nd-space, и каждый слайд offer-slider__slide делаете ссылкой - недостаток активной будет только область слайда
2. Вешаете прослушку на js-offer-slider-container: document.querySelector('js-offer-slider-container').swiper.on('slideChange', () => {}); получаете активный слайд и меняете ссылку на соответсвующую ему. api для swiper можно посмотреть здесь https://swiperjs.com/api/

**Comment by ASergej** [comment]
Спасибо.
