### ISSUE TITLE
Account company info  birthDate field

### ISSUE THREAD

**Issue by ASergej** [verstaburo/Space-pool#76]
https://verstaburo.github.io/Space-pool/guest-account-company.html
Нужно поменять формат поля birthDate с 'YYYY / MM / DD' на 'DD/MM/YYYY'

**Comment by allkrain** [comment]
Допустимо изменить эту маску во всех полях c датой рождения или нужно только в этом конкретном случае?

**Comment by ASergej** [comment]
Можно менять на всех полях с датой рождения.

**Comment by allkrain** [comment]
Сделано

**Comment by ASergej** [comment]
Спасибо.
