### ISSUE TITLE
Мешает JS

### ISSUE THREAD

**Issue by alexxxxey** [verstaburo/Space-pool#8]
Уберите плз код из js файла. Он нам не пригоден, а на сервер отправляет запрос
$.ajax('assets/data/templates.json', {
    dataType: 'json',
    async: false,
    type: 'GET',
    complete(answer) {
      window.templates = answer.responseJSON;
    },
  });

**Comment by allkrain** [comment]
Этот код тянет шаблон для превюшек фотографий в форме на странице https://verstaburo.github.io/Space-pool/new-space-step41.html. Т. е. я могу удалить его только совместно с кодом обслуживающим загрузку фотографий и их предпросмотр. Если вы берете написание этого кода на себя, то без проблем.

**Comment by alexxxxey** [comment]
Я понял что он тянет. Просто:
1) ajax url захардкожен
2) ajax делается при рефреше любой страницы.
3) непонятно, зачем вообще тянуть темплейт с помощью ajax.

Мне надо:
1) что б я мог менять ajax url (скажем считывать с data атрибута какого-то)
2) сделать ajax загрузку шаблона только в том месте, где надо.

**Comment by allkrain** [comment]
Я могу не тянуть темплейт через ajax - но тогда уже он будет захардкожен и повлиять на него у вас не получиться

**Comment by alexxxxey** [comment]
Я имел ввиду брать темплейт из какого-то либо скрытого дива, остально оставить как есть. 
В общем нам нужно или влиять на ajaxurl + убрать загрузку на каждой странице или темплейт в html

**Comment by allkrain** [comment]
У блока .uploader теперь есть data-url-template - куда можно вписать url для ajax. Запрос будет делаться при взаимодействии с этим блоком.
