### ISSUE TITLE
Search result

### ISSUE THREAD

**Issue by alexxxxey** [verstaburo/Space-pool#9]
https://verstaburo.github.io/Space-pool/search-result.html

К каждому options для Area, City, Workplace type мне нужно доставить data-redirect атрибут. Как мне к data-redirect обратиться, при select change ?

**Comment by allkrain** [comment]
Choices удаляет все data-атрибуты у опций на сколько я знаю. На данный момент лучшее, что могу предложить помещать в value у options json объект или строку, которая кроме собственно value будет содержать и редирект

**Comment by alexxxxey** [comment]
К сожалению нам не подойдет такое решение, на намного больше переделать придется.  Точно он удаляет? Если это этот пакет https://github.com/jshjohnson/Choices/issues/543 то должен работать ..

**Comment by allkrain** [comment]
Да это этот пакет. Попробуй.
