### ISSUE TITLE
Глобальная функция для открытия popup Share на странице space

### ISSUE THREAD

**Issue by nbogdani4** [verstaburo/Space-pool#90]
Нужен метод в globalFunctions для открытия Share popup на странице Space

**Comment by allkrain** [comment]
window.globalFunctions.openPopover - в качестве аргумента принимает элемент возле которого должен появится share popup, у элемента должен быть href с id share popup.

В качестве альтернативы можно просто добавить share popup  класс 'is-opened' и задать координаты left, top
